"""PDB and SDF output must be valid, unique-named, and re-readable."""

from __future__ import annotations

import pytest
from rdkit import Chem

from ligand3d.embed import embed, embed_multi
from ligand3d.molecule import from_smiles
from ligand3d.write import (
    ConformerRecord,
    to_pdb_block,
    verify_pdb_roundtrip,
    write_pdb,
    write_sdf,
)


@pytest.fixture
def quinuclidinone():
    return embed(from_smiles("O=C1CN2CCC1CC2"))


def atom_lines(block: str) -> list[str]:
    return [ln for ln in block.splitlines() if ln.startswith(("ATOM", "HETATM"))]


class TestPDBBlock:
    def test_writes_one_record_per_atom(self, quinuclidinone):
        block = to_pdb_block(quinuclidinone, resname="QUI")
        assert len(atom_lines(block)) == quinuclidinone.GetNumAtoms()

    def test_atom_names_are_unique(self, quinuclidinone):
        """PDB readers key on atom name within a residue; duplicates corrupt it."""
        names = [ln[12:16] for ln in atom_lines(to_pdb_block(quinuclidinone))]
        assert len(set(names)) == len(names)

    def test_residue_name_is_honoured(self, quinuclidinone):
        block = to_pdb_block(quinuclidinone, resname="QUI")
        assert all(ln[17:20] == "QUI" for ln in atom_lines(block))

    def test_residue_name_is_truncated_to_three_characters(self, quinuclidinone):
        block = to_pdb_block(quinuclidinone, resname="TOOLONG")
        assert all(ln[17:20] == "TOO" for ln in atom_lines(block))

    def test_connectivity_is_written(self, quinuclidinone):
        assert any(ln.startswith("CONECT") for ln in to_pdb_block(quinuclidinone).splitlines())

    def test_element_column_is_populated(self, quinuclidinone):
        for line in atom_lines(to_pdb_block(quinuclidinone)):
            assert line[76:78].strip(), f"missing element in {line!r}"

    def test_formal_charges_are_preserved(self):
        """PDB columns 79-80 carry the charge; losing them changes the molecule."""
        mol_3d = embed(from_smiles("[NH3+]CC1(CC(=O)[O-])CCCCC1"))
        charge_fields = {ln[76:80] for ln in atom_lines(to_pdb_block(mol_3d))}
        assert " N1+" in charge_fields
        assert " O1-" in charge_fields

    def test_provenance_remarks_are_present(self, quinuclidinone):
        block = to_pdb_block(quinuclidinone, smiles="O=C1CN2CCC1CC2")
        assert "REMARK   1 GENERATED BY LIGAND3D" in block
        assert "O=C1CN2CCC1CC2" in block

    def test_no_line_exceeds_eighty_columns(self, quinuclidinone):
        block = to_pdb_block(
            quinuclidinone,
            smiles="C" * 200,  # absurd SMILES must still be truncated safely
            extra_remarks=["X" * 200],
        )
        assert all(len(line) <= 80 for line in block.splitlines())

    def test_single_conformer_has_no_model_records(self, quinuclidinone):
        assert "MODEL" not in to_pdb_block(quinuclidinone)

    def test_ends_with_end_record(self, quinuclidinone):
        assert to_pdb_block(quinuclidinone).strip().endswith("END")

    def test_raises_without_conformers(self):
        mol = Chem.AddHs(Chem.MolFromSmiles("CCO"))
        with pytest.raises(ValueError, match="no conformers"):
            to_pdb_block(mol)


class TestMultiConformer:
    @pytest.fixture
    def octanol(self):
        return embed_multi(from_smiles("CCCCCCCCO"), n_confs=5)

    def test_each_conformer_becomes_a_model(self, octanol):
        block = to_pdb_block(octanol)
        n_models = block.count("MODEL")
        assert n_models == octanol.GetNumConformers()
        assert block.count("ENDMDL") == n_models

    def test_connectivity_is_written_once_for_the_ensemble(self, octanol):
        """CONECT refers to serial numbers shared by every model."""
        block = to_pdb_block(octanol)
        conect = [ln for ln in block.splitlines() if ln.startswith("CONECT")]
        single = to_pdb_block(embed(from_smiles("CCCCCCCCO")))
        assert len(conect) == len(
            [ln for ln in single.splitlines() if ln.startswith("CONECT")]
        )


class TestFiles:
    def test_pdb_reads_back_in_rdkit(self, quinuclidinone, tmp_path):
        path = write_pdb(tmp_path / "out.pdb", quinuclidinone, resname="QUI")
        verify_pdb_roundtrip(path, quinuclidinone)

    def test_sdf_preserves_bond_orders(self, tmp_path):
        """PDB loses bond orders, which is exactly why the sidecar exists."""
        molecule = from_smiles("O=C1CN2CCC1CC2")
        mol_3d = embed(molecule)
        path = write_sdf(tmp_path / "out.sdf", mol_3d)

        back = next(iter(Chem.SDMolSupplier(str(path), removeHs=False)))
        assert Chem.MolToSmiles(Chem.RemoveHs(back)) == molecule.smiles

    def test_sdf_carries_energy_metadata(self, quinuclidinone, tmp_path):
        records = [
            ConformerRecord(
                conf_id=0, energy=-12.5, backend="mmff94", converged=True, energy_kind="strain"
            )
        ]
        path = write_sdf(tmp_path / "out.sdf", quinuclidinone, records=records)
        back = next(iter(Chem.SDMolSupplier(str(path), removeHs=False)))

        assert float(back.GetProp("ligand3d_energy")) == pytest.approx(-12.5)
        assert back.GetProp("ligand3d_backend") == "mmff94"
        assert back.GetProp("ligand3d_energy_kind") == "strain"

    def test_total_energies_are_labelled_as_absolute(self, quinuclidinone, tmp_path):
        records = [
            ConformerRecord(conf_id=0, energy=-24487.0, backend="gfn2", energy_kind="total")
        ]
        path = write_pdb(tmp_path / "out.pdb", quinuclidinone, records=records)
        text = path.read_text()
        assert "TOTAL ENERGIES FROM GFN2" in text
        assert "ABSOLUTE ELECTRONIC ENERGIES" in text

    def test_parent_directories_are_created(self, quinuclidinone, tmp_path):
        path = write_pdb(tmp_path / "a" / "b" / "out.pdb", quinuclidinone)
        assert path.exists()
