"""Output writers.

PDB is the requested format but it is a lossy one: it stores elements and
coordinates, and encodes bond orders only as a duplicated-CONECT convention that
many readers ignore. So every PDB is written with an SDF sidecar alongside it,
which round-trips bond orders, charges, and stereo perfectly.
"""

from __future__ import annotations

import datetime as _dt
from dataclasses import dataclass
from pathlib import Path

from rdkit import Chem

from .molecule import rdkit_quiet

_MAX_RESNAME = 3

# Digits used to keep atom names inside the four columns PDB allows. Base 36
# gets a single-letter element to 46655 atoms, far beyond anything this tool
# will be handed.
_BASE36 = "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ"


def _base36(n: int) -> str:
    if n == 0:
        return "0"
    out = ""
    while n:
        n, r = divmod(n, 36)
        out = _BASE36[r] + out
    return out


def _atom_name(symbol: str, index: int) -> str:
    """Build a unique four-character PDB atom name.

    Atom names occupy columns 13-16, and the convention that keeps one- and
    two-letter elements aligned is to indent single-letter elements by one
    space. That leaves only two digits for a single-letter element, so a
    molecule with 100 or more carbons used to truncate C100 to "C10" and
    collide with the real C10 — silently producing a file whose atom names are
    not unique, which is exactly what PDB readers key on.

    Past the point where decimal no longer fits, the space is reclaimed and
    then the counter switches to base 36.
    """
    decimal = f"{symbol}{index}"
    if len(symbol) == 1 and len(decimal) <= 3:
        return f" {decimal}".ljust(4)
    if len(decimal) <= 4:
        return decimal.ljust(4)

    packed = f"{symbol}{_base36(index)}"
    if len(packed) <= 4:
        return packed.ljust(4)
    # Nothing sane reaches here; truncate rather than emit a malformed column.
    return packed[:4]


@dataclass(frozen=True)
class ConformerRecord:
    """One conformer plus whatever the pipeline learned about it."""

    conf_id: int
    energy: float | None = None
    energy_unit: str = "kcal/mol"
    energy_kind: str = "strain"
    backend: str | None = None
    converged: bool | None = None


def assign_pdb_names(mol: Chem.Mol, resname: str = "LIG", chain: str = "A") -> Chem.Mol:
    """Give every atom a unique PDB atom name within the residue.

    RDKit's default naming is already unique, but it is derived from atom order
    and does not survive editing. Doing it explicitly means the names are stable
    and predictable: C1, C2, N1, O1, H1 ... numbered per element in atom order.
    """
    resname = (resname or "LIG").upper()[:_MAX_RESNAME]
    counts: dict[str, int] = {}
    out = Chem.Mol(mol)
    for atom in out.GetAtoms():
        sym = atom.GetSymbol().upper()
        counts[sym] = counts.get(sym, 0) + 1
        name = _atom_name(sym, counts[sym])
        info = Chem.AtomPDBResidueInfo()
        info.SetName(name)
        info.SetResidueName(resname.ljust(3))
        info.SetResidueNumber(1)
        info.SetChainId(chain)
        info.SetIsHeteroAtom(True)
        info.SetOccupancy(1.0)
        info.SetTempFactor(0.0)
        atom.SetMonomerInfo(info)
    return out


def _remarks(
    smiles: str,
    records: list[ConformerRecord],
    extra: list[str] | None = None,
) -> list[str]:
    stamp = _dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines = [
        "REMARK   1 GENERATED BY LIGAND3D",
        f"REMARK   1 DATE {stamp}",
        f"REMARK   1 SMILES {smiles}"[:80],
    ]
    for line in extra or []:
        lines.append(f"REMARK   1 {line}"[:80])
    if records and any(r.energy is not None for r in records):
        unit = records[0].energy_unit
        backend = records[0].backend or "unknown"
        kind = records[0].energy_kind
        lines.append(f"REMARK   2 {kind.upper()} ENERGIES FROM {backend.upper()} IN {unit.upper()}"[:80])
        if kind == "total":
            lines.append(
                "REMARK   2 THESE ARE ABSOLUTE ELECTRONIC ENERGIES; ONLY DIFFERENCES"[:80]
            )
            lines.append("REMARK   2 BETWEEN CONFORMERS OF THIS MOLECULE ARE MEANINGFUL"[:80])
        for n, rec in enumerate(records, start=1):
            if rec.energy is None:
                continue
            flag = "" if rec.converged is not False else " (NOT CONVERGED)"
            lines.append(f"REMARK   2 MODEL {n:5d} ENERGY {rec.energy:16.6f}{flag}"[:80])
    return lines


def to_pdb_block(
    mol: Chem.Mol,
    records: list[ConformerRecord] | None = None,
    resname: str = "LIG",
    smiles: str | None = None,
    extra_remarks: list[str] | None = None,
) -> str:
    """Render one or many conformers as a single PDB block.

    Multiple conformers become MODEL/ENDMDL records with one shared set of CONECT
    records at the end, which is how the format expects an ensemble of the same
    molecule to be stored.
    """
    named = assign_pdb_names(mol, resname=resname)
    conf_ids = [c.GetId() for c in named.GetConformers()]
    if not conf_ids:
        raise ValueError("molecule has no conformers to write")
    records = records or [ConformerRecord(conf_id=c) for c in conf_ids]
    smiles = smiles or Chem.MolToSmiles(Chem.RemoveHs(named))

    lines: list[str] = _remarks(smiles, records, extra_remarks)

    conect: list[str] = []
    multi = len(conf_ids) > 1
    for n, cid in enumerate(conf_ids, start=1):
        with rdkit_quiet():
            block = Chem.MolToPDBBlock(named, confId=cid, flavor=0)
        atom_lines = [ln for ln in block.splitlines() if ln.startswith(("ATOM", "HETATM"))]
        if not conect:
            conect = [ln for ln in block.splitlines() if ln.startswith("CONECT")]
        if multi:
            lines.append(f"MODEL     {n:4d}")
        lines.extend(atom_lines)
        if multi:
            lines.append("ENDMDL")
    lines.extend(conect)
    lines.append("END")
    return "\n".join(lines) + "\n"


def write_pdb(
    path: str | Path,
    mol: Chem.Mol,
    records: list[ConformerRecord] | None = None,
    resname: str = "LIG",
    smiles: str | None = None,
    extra_remarks: list[str] | None = None,
) -> Path:
    """Write a PDB file and return its path."""
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(
        to_pdb_block(
            mol, records=records, resname=resname, smiles=smiles, extra_remarks=extra_remarks
        )
    )
    return p


def write_sdf(
    path: str | Path,
    mol: Chem.Mol,
    records: list[ConformerRecord] | None = None,
    name: str = "ligand3d",
) -> Path:
    """Write the same conformers as SDF, preserving bond orders and charges."""
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    conf_ids = [c.GetId() for c in mol.GetConformers()]
    by_id = {r.conf_id: r for r in (records or [])}
    with Chem.SDWriter(str(p)) as writer:
        for n, cid in enumerate(conf_ids, start=1):
            work = Chem.Mol(mol)
            work.SetProp("_Name", f"{name}_conf{n}" if len(conf_ids) > 1 else name)
            rec = by_id.get(cid)
            if rec is not None:
                if rec.energy is not None:
                    work.SetProp("ligand3d_energy", f"{rec.energy:.6f}")
                    work.SetProp("ligand3d_energy_unit", rec.energy_unit)
                    work.SetProp("ligand3d_energy_kind", rec.energy_kind)
                if rec.backend:
                    work.SetProp("ligand3d_backend", rec.backend)
                if rec.converged is not None:
                    work.SetProp("ligand3d_converged", str(rec.converged))
            writer.write(work, confId=cid)
    return p


def verify_pdb_roundtrip(path: str | Path, reference: Chem.Mol) -> None:
    """Confirm the file we just wrote reads back as the molecule we meant.

    Cheap insurance against a malformed record, and it catches the class of bug
    where output looks fine in a text editor but no parser accepts it.
    """
    from .errors import Ligand3DError

    with rdkit_quiet():
        back = Chem.MolFromPDBFile(str(path), removeHs=False, sanitize=False)
    if back is None:
        raise Ligand3DError(f"wrote {path} but RDKit cannot read it back")
    if back.GetNumAtoms() != reference.GetNumAtoms():
        raise Ligand3DError(
            f"wrote {path} with {reference.GetNumAtoms()} atoms but it reads back "
            f"as {back.GetNumAtoms()}"
        )
    names = [
        a.GetMonomerInfo().GetName()
        for a in back.GetAtoms()
        if a.GetMonomerInfo() is not None
    ]
    if names and len(set(names)) != len(names):
        raise Ligand3DError(f"{path} has duplicate atom names within one residue")


# --------------------------------------------------------------------------
# mmCIF
# --------------------------------------------------------------------------

_CIF_BOND_ORDER = {
    Chem.BondType.SINGLE: "SING",
    Chem.BondType.DOUBLE: "DOUB",
    Chem.BondType.TRIPLE: "TRIP",
    Chem.BondType.QUADRUPLE: "QUAD",
    Chem.BondType.AROMATIC: "SING",  # value_order with aromatic_flag Y
}


def cif_available() -> bool:
    """True if gemmi is importable, which is what does the mmCIF conversion."""
    import importlib.util

    return importlib.util.find_spec("gemmi") is not None


def to_cif_string(
    mol: Chem.Mol,
    records: list[ConformerRecord] | None = None,
    resname: str = "LIG",
    smiles: str | None = None,
    name: str = "ligand3d",
    extra_remarks: list[str] | None = None,
) -> str:
    """Render conformers as mmCIF.

    Coordinates go through gemmi, which produces a standard `_atom_site` loop
    with `pdbx_PDB_model_num` distinguishing conformers — the same convention a
    multi-model PDB uses, and what structural tools expect.

    A `_chem_comp_bond` loop is appended with bond orders and aromatic flags.
    That is the one thing PDB genuinely cannot carry, so including it here makes
    the mmCIF self-sufficient rather than needing the SDF sidecar to be read
    alongside it.
    """
    try:
        import gemmi
    except ImportError as exc:  # pragma: no cover - guarded by cif_available
        from .errors import Ligand3DError

        raise Ligand3DError(
            "writing mmCIF needs gemmi. Install it with: pip install gemmi"
        ) from exc

    named = assign_pdb_names(mol, resname=resname)
    smiles = smiles or Chem.MolToSmiles(Chem.RemoveHs(named))

    pdb_block = to_pdb_block(
        named, records=records, resname=resname, smiles=smiles,
        extra_remarks=extra_remarks,
    )
    structure = gemmi.read_pdb_string(pdb_block)
    # Without a name, gemmi labels the entry "string" after its input.
    structure.name = name
    structure.setup_entities()

    document = structure.make_mmcif_document()
    block = document.sole_block()

    _add_bond_loop(block, named, resname=resname)
    _add_provenance(block, smiles=smiles, records=records)

    return document.as_string()


def _add_bond_loop(block, mol: Chem.Mol, resname: str) -> None:
    """Append `_chem_comp_bond`, the bond orders PDB cannot represent."""
    comp = (resname or "LIG").upper()[:_MAX_RESNAME]
    names = [
        atom.GetMonomerInfo().GetName().strip()
        if atom.GetMonomerInfo() is not None
        else f"{atom.GetSymbol()}{atom.GetIdx()}"
        for atom in mol.GetAtoms()
    ]

    loop = block.init_loop(
        "_chem_comp_bond.",
        ["comp_id", "atom_id_1", "atom_id_2", "value_order", "pdbx_aromatic_flag"],
    )
    for bond in mol.GetBonds():
        order = _CIF_BOND_ORDER.get(bond.GetBondType(), "SING")
        aromatic = "Y" if bond.GetIsAromatic() else "N"
        loop.add_row(
            [comp, names[bond.GetBeginAtomIdx()], names[bond.GetEndAtomIdx()],
             order, aromatic]
        )


def _add_provenance(block, smiles: str, records: list[ConformerRecord] | None) -> None:
    """Record what produced this file, the way the PDB REMARKs do."""
    from . import __version__

    stamp = _dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines = [
        f"Generated by ligand3d {__version__} on {stamp}",
        f"SMILES {smiles}",
    ]
    if records and records[0].energy is not None:
        first = records[0]
        kind = "total electronic" if first.energy_kind == "total" else "strain"
        lines.append(
            f"{kind} energies from {first.backend} in {first.energy_unit}; "
            "only differences between conformers of this molecule are meaningful"
        )
        for n, record in enumerate(records, start=1):
            if record.energy is not None:
                lines.append(f"model {n} energy {record.energy:.6f}")

    loop = block.init_loop("_ligand3d.", ["ordinal", "detail"])
    for n, line in enumerate(lines, start=1):
        loop.add_row([str(n), gemmi_quote(line)])


def gemmi_quote(text: str) -> str:
    """Quote a CIF value that contains spaces."""
    if not text:
        return "?"
    if any(ch in text for ch in " \t'\"") or text[0] in "_#$[]":
        escaped = text.replace("'", "\\'")
        return f"'{escaped}'"
    return text


def write_cif(
    path: str | Path,
    mol: Chem.Mol,
    records: list[ConformerRecord] | None = None,
    resname: str = "LIG",
    smiles: str | None = None,
    extra_remarks: list[str] | None = None,
) -> Path:
    """Write an mmCIF file and return its path."""
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(
        to_cif_string(
            mol, records=records, resname=resname, smiles=smiles,
            name=p.stem, extra_remarks=extra_remarks,
        )
    )
    return p


def verify_cif_roundtrip(path: str | Path, reference: Chem.Mol) -> None:
    """Confirm the mmCIF we wrote parses and holds the right atoms."""
    from .errors import Ligand3DError

    try:
        import gemmi
    except ImportError:  # pragma: no cover
        return
    try:
        structure = gemmi.read_structure(str(path))
    except Exception as exc:
        raise Ligand3DError(f"wrote {path} but gemmi cannot read it back: {exc}") from exc
    if len(structure) == 0:
        raise Ligand3DError(f"{path} contains no models")
    n_atoms = sum(len(residue) for chain in structure[0] for residue in chain)
    if n_atoms != reference.GetNumAtoms():
        raise Ligand3DError(
            f"wrote {path} with {reference.GetNumAtoms()} atoms but it reads back "
            f"as {n_atoms}"
        )


# --------------------------------------------------------------------------
# Minimization trajectory
# --------------------------------------------------------------------------


def write_trajectory(
    path: str | Path,
    mol: Chem.Mol,
    frames: list,
    resname: str = "LIG",
    energies: list[float] | None = None,
    stage_labels: list[str] | None = None,
) -> Path:
    """Write the optimizer path as a multi-model PDB.

    One MODEL per step, in order, so the file animates in PyMOL, ChimeraX, or
    VMD. Energies and the method responsible for each frame go into REMARKs
    rather than being lost, because a trajectory whose frames you cannot label
    is much less useful than one you can.
    """
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    if not frames:
        raise ValueError("no frames to write")

    from rdkit.Geometry import Point3D

    named = assign_pdb_names(mol, resname=resname)
    template = Chem.Mol(named)
    template.RemoveAllConformers()
    base = Chem.Conformer(named.GetConformer(named.GetConformers()[0].GetId()))
    template.AddConformer(base, assignId=True)
    conf = template.GetConformer(0)

    stamp = _dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines = [
        "REMARK   1 LIGAND3D MINIMIZATION TRAJECTORY",
        f"REMARK   1 DATE {stamp}",
        f"REMARK   1 {len(frames)} FRAMES, ONE PER OPTIMIZER STEP"[:80],
    ]
    if stage_labels:
        for label in dict.fromkeys(stage_labels):
            lines.append(f"REMARK   1 METHOD {label}"[:80])

    conect: list[str] = []
    for index, positions in enumerate(frames, start=1):
        for i, (x, y, z) in enumerate(positions):
            conf.SetAtomPosition(i, Point3D(float(x), float(y), float(z)))
        with rdkit_quiet():
            block = Chem.MolToPDBBlock(template, confId=0, flavor=0)
        if not conect:
            conect = [ln for ln in block.splitlines() if ln.startswith("CONECT")]

        header = f"MODEL     {index:4d}"
        lines.append(header)
        if energies is not None and index - 1 < len(energies):
            label = stage_labels[index - 1] if stage_labels and index - 1 < len(stage_labels) else ""
            lines.append(
                f"REMARK   2 FRAME {index:5d} ENERGY {energies[index - 1]:16.6f} {label}"[:80]
            )
        lines.extend(
            ln for ln in block.splitlines() if ln.startswith(("ATOM", "HETATM"))
        )
        lines.append("ENDMDL")

    lines.extend(conect)
    lines.append("END")
    p.write_text("\n".join(lines) + "\n")
    return p
