"""Output writers.

PDB is the requested format but it is a lossy one: it stores elements and
coordinates, and encodes bond orders only as a duplicated-CONECT convention that
many readers ignore. So every PDB is written with an SDF sidecar alongside it,
which round-trips bond orders, charges, and stereo perfectly.
"""

from __future__ import annotations

import datetime as _dt
from dataclasses import dataclass
from pathlib import Path

from rdkit import Chem

from .molecule import rdkit_quiet

_MAX_RESNAME = 3


@dataclass(frozen=True)
class ConformerRecord:
    """One conformer plus whatever the pipeline learned about it."""

    conf_id: int
    energy: float | None = None
    energy_unit: str = "kcal/mol"
    energy_kind: str = "strain"
    backend: str | None = None
    converged: bool | None = None


def assign_pdb_names(mol: Chem.Mol, resname: str = "LIG", chain: str = "A") -> Chem.Mol:
    """Give every atom a unique PDB atom name within the residue.

    RDKit's default naming is already unique, but it is derived from atom order
    and does not survive editing. Doing it explicitly means the names are stable
    and predictable: C1, C2, N1, O1, H1 ... numbered per element in atom order.
    """
    resname = (resname or "LIG").upper()[:_MAX_RESNAME]
    counts: dict[str, int] = {}
    out = Chem.Mol(mol)
    for atom in out.GetAtoms():
        sym = atom.GetSymbol().upper()
        counts[sym] = counts.get(sym, 0) + 1
        # PDB atom names live in columns 13-16. The convention that keeps
        # one- and two-letter elements aligned is to left-pad single-letter
        # element names by one space.
        label = f"{sym}{counts[sym]}"
        if len(sym) == 1:
            name = f" {label}".ljust(4)[:4]
        else:
            name = label.ljust(4)[:4]
        info = Chem.AtomPDBResidueInfo()
        info.SetName(name)
        info.SetResidueName(resname.ljust(3))
        info.SetResidueNumber(1)
        info.SetChainId(chain)
        info.SetIsHeteroAtom(True)
        info.SetOccupancy(1.0)
        info.SetTempFactor(0.0)
        atom.SetMonomerInfo(info)
    return out


def _remarks(
    smiles: str,
    records: list[ConformerRecord],
    extra: list[str] | None = None,
) -> list[str]:
    stamp = _dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    lines = [
        "REMARK   1 GENERATED BY LIGAND3D",
        f"REMARK   1 DATE {stamp}",
        f"REMARK   1 SMILES {smiles}"[:80],
    ]
    for line in extra or []:
        lines.append(f"REMARK   1 {line}"[:80])
    if records and any(r.energy is not None for r in records):
        unit = records[0].energy_unit
        backend = records[0].backend or "unknown"
        kind = records[0].energy_kind
        lines.append(f"REMARK   2 {kind.upper()} ENERGIES FROM {backend.upper()} IN {unit.upper()}"[:80])
        if kind == "total":
            lines.append(
                "REMARK   2 THESE ARE ABSOLUTE ELECTRONIC ENERGIES; ONLY DIFFERENCES"[:80]
            )
            lines.append("REMARK   2 BETWEEN CONFORMERS OF THIS MOLECULE ARE MEANINGFUL"[:80])
        for n, rec in enumerate(records, start=1):
            if rec.energy is None:
                continue
            flag = "" if rec.converged is not False else " (NOT CONVERGED)"
            lines.append(f"REMARK   2 MODEL {n:5d} ENERGY {rec.energy:16.6f}{flag}"[:80])
    return lines


def to_pdb_block(
    mol: Chem.Mol,
    records: list[ConformerRecord] | None = None,
    resname: str = "LIG",
    smiles: str | None = None,
    extra_remarks: list[str] | None = None,
) -> str:
    """Render one or many conformers as a single PDB block.

    Multiple conformers become MODEL/ENDMDL records with one shared set of CONECT
    records at the end, which is how the format expects an ensemble of the same
    molecule to be stored.
    """
    named = assign_pdb_names(mol, resname=resname)
    conf_ids = [c.GetId() for c in named.GetConformers()]
    if not conf_ids:
        raise ValueError("molecule has no conformers to write")
    records = records or [ConformerRecord(conf_id=c) for c in conf_ids]
    smiles = smiles or Chem.MolToSmiles(Chem.RemoveHs(named))

    lines: list[str] = _remarks(smiles, records, extra_remarks)

    conect: list[str] = []
    multi = len(conf_ids) > 1
    for n, cid in enumerate(conf_ids, start=1):
        with rdkit_quiet():
            block = Chem.MolToPDBBlock(named, confId=cid, flavor=0)
        atom_lines = [ln for ln in block.splitlines() if ln.startswith(("ATOM", "HETATM"))]
        if not conect:
            conect = [ln for ln in block.splitlines() if ln.startswith("CONECT")]
        if multi:
            lines.append(f"MODEL     {n:4d}")
        lines.extend(atom_lines)
        if multi:
            lines.append("ENDMDL")
    lines.extend(conect)
    lines.append("END")
    return "\n".join(lines) + "\n"


def write_pdb(
    path: str | Path,
    mol: Chem.Mol,
    records: list[ConformerRecord] | None = None,
    resname: str = "LIG",
    smiles: str | None = None,
    extra_remarks: list[str] | None = None,
) -> Path:
    """Write a PDB file and return its path."""
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(
        to_pdb_block(
            mol, records=records, resname=resname, smiles=smiles, extra_remarks=extra_remarks
        )
    )
    return p


def write_sdf(
    path: str | Path,
    mol: Chem.Mol,
    records: list[ConformerRecord] | None = None,
    name: str = "ligand3d",
) -> Path:
    """Write the same conformers as SDF, preserving bond orders and charges."""
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    conf_ids = [c.GetId() for c in mol.GetConformers()]
    by_id = {r.conf_id: r for r in (records or [])}
    with Chem.SDWriter(str(p)) as writer:
        for n, cid in enumerate(conf_ids, start=1):
            work = Chem.Mol(mol)
            work.SetProp("_Name", f"{name}_conf{n}" if len(conf_ids) > 1 else name)
            rec = by_id.get(cid)
            if rec is not None:
                if rec.energy is not None:
                    work.SetProp("ligand3d_energy", f"{rec.energy:.6f}")
                    work.SetProp("ligand3d_energy_unit", rec.energy_unit)
                    work.SetProp("ligand3d_energy_kind", rec.energy_kind)
                if rec.backend:
                    work.SetProp("ligand3d_backend", rec.backend)
                if rec.converged is not None:
                    work.SetProp("ligand3d_converged", str(rec.converged))
            writer.write(work, confId=cid)
    return p


def verify_pdb_roundtrip(path: str | Path, reference: Chem.Mol) -> None:
    """Confirm the file we just wrote reads back as the molecule we meant.

    Cheap insurance against a malformed record, and it catches the class of bug
    where output looks fine in a text editor but no parser accepts it.
    """
    from .errors import Ligand3DError

    with rdkit_quiet():
        back = Chem.MolFromPDBFile(str(path), removeHs=False, sanitize=False)
    if back is None:
        raise Ligand3DError(f"wrote {path} but RDKit cannot read it back")
    if back.GetNumAtoms() != reference.GetNumAtoms():
        raise Ligand3DError(
            f"wrote {path} with {reference.GetNumAtoms()} atoms but it reads back "
            f"as {back.GetNumAtoms()}"
        )
    names = [
        a.GetMonomerInfo().GetName()
        for a in back.GetAtoms()
        if a.GetMonomerInfo() is not None
    ]
    if names and len(set(names)) != len(names):
        raise Ligand3DError(f"{path} has duplicate atom names within one residue")
